name: Publish docs website
on:
  workflow_dispatch:
  push:
    paths:
      - docs/**
    branches:
      - master

jobs:
  publish:
    name: Build and publish

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        with:
          config: docs

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
          directory: ./
          branch: docs-website