name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/'
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest
        with:
          config: docs

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
          config: docs
          branch: docs-website